// TifMaxi-main/frontend/src/components/tables/Table.tsx
'use client';

import { useState } from 'react';

interface Column<T> {
  key: keyof T;
  label: string;
  render?: (value: any, item: T, index: number) => React.ReactNode;
  sortable?: boolean;
  width?: string;
}

interface TableProps<T> {
  data: T[];
  columns: Column<T>[];
  loading?: boolean;
  error?: string;
  emptyMessage?: string;
  onRowClick?: (item: T) => void;
  onSort?: (key: keyof T, direction: 'asc' | 'desc') => void;
  sortKey?: keyof T;
  sortDirection?: 'asc' | 'desc';
  actions?: (item: T) => React.ReactNode;
}

export function Table<T extends Record<string, any>>({
  data,
  columns,
  loading = false,
  error,
  emptyMessage = 'No hay datos disponibles',
  onRowClick,
  onSort,
  sortKey,
  sortDirection,
  actions,
}: TableProps<T>) {
  const [hoveredRow, setHoveredRow] = useState<number | null>(null);

  const handleSort = (column: Column<T>) => {
    if (!column.sortable || !onSort) return;
    
    const newDirection = 
      sortKey === column.key && sortDirection === 'asc' ? 'desc' : 'asc';
    onSort(column.key, newDirection);
  };

  const renderSortIcon = (column: Column<T>) => {
    if (!column.sortable || !onSort) return null;

    if (sortKey !== column.key) {
      return (
        <svg className="ml-1 h-4 w-4 text-gray-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M7 11l5-5m0 0l5 5m-5-5v12" />
        </svg>
      );
    }

    return (
      <svg 
        className={`ml-1 h-4 w-4 transform transition-transform ${
          sortDirection === 'desc' ? 'rotate-180' : ''
        }`} 
        fill="none" 
        viewBox="0 0 24 24" 
        stroke="currentColor"
      >
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M7 11l5-5m0 0l5 5m-5-5v12" />
      </svg>
    );
  };

  if (loading) {
    return (
      <div className="overflow-hidden shadow ring-1 ring-black ring-opacity-5 md:rounded-lg">
        <div className="bg-gray-50 px-6 py-3">
          <div className="h-4 bg-gray-200 rounded w-1/4 animate-pulse"></div>
        </div>
        <div className="bg-white divide-y divide-gray-200">
          {[...Array(5)].map((_, i) => (
            <div key={i} className="px-6 py-4 animate-pulse">
              <div className="flex space-x-4">
                <div className="h-4 bg-gray-200 rounded flex-1"></div>
                <div className="h-4 bg-gray-200 rounded flex-1"></div>
                <div className="h-4 bg-gray-200 rounded flex-1"></div>
              </div>
            </div>
          ))}
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="bg-red-50 border border-red-200 text-red-600 px-4 py-3 rounded">
        Error: {error}
      </div>
    );
  }

  if (data.length === 0) {
    return (
      <div className="bg-white border border-gray-200 rounded-lg p-8 text-center">
        <svg className="mx-auto h-12 w-12 text-gray-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
        </svg>
        <h3 className="mt-2 text-sm font-medium text-gray-900">Sin datos</h3>
        <p className="mt-1 text-sm text-gray-500">{emptyMessage}</p>
      </div>
    );
  }

  return (
    <div className="overflow-hidden shadow ring-1 ring-black ring-opacity-5 md:rounded-lg">
      <table className="min-w-full divide-y divide-gray-300">
        <thead className="bg-gray-50">
          <tr>
            {columns.map((column) => (
              <th
                key={String(column.key)}
                scope="col"
                className={`px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider ${
                  column.sortable && onSort ? 'cursor-pointer hover:bg-gray-100' : ''
                }`}
                style={{ width: column.width }}
                onClick={() => handleSort(column)}
              >
                <div className="flex items-center">
                  {column.label}
                  {renderSortIcon(column)}
                </div>
              </th>
            ))}
            {actions && (
              <th scope="col" className="relative px-6 py-3">
                <span className="sr-only">Acciones</span>
              </th>
            )}
          </tr>
        </thead>
        <tbody className="bg-white divide-y divide-gray-200">
          {data.map((item, index) => (
            <tr
              key={item.id || index}
              className={`${
                onRowClick ? 'cursor-pointer hover:bg-gray-50' : ''
              } ${hoveredRow === index ? 'bg-gray-50' : ''}`}
              onClick={() => onRowClick?.(item)}
              onMouseEnter={() => setHoveredRow(index)}
              onMouseLeave={() => setHoveredRow(null)}
            >
              {columns.map((column) => (
                <td key={String(column.key)} className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                  {column.render 
                    ? column.render(item[column.key], item, index)
                    : item[column.key]
                  }
                </td>
              ))}
              {actions && (
                <td className="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                  {actions(item)}
                </td>
              )}
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

// TifMaxi-main/resources/js/components/ui/Table.vue
<template>
    <div class="overflow-hidden shadow ring-1 ring-black ring-opacity-5 rounded-lg">
        <table class="min-w-full divide-y divide-gray-300">
            <thead class="bg-gray-50">
                <tr>
                    <th
                        v-for="column in columns"
                        :key="column.key"
                        :class="[
                            'px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider',
                            column.class || ''
                        ]"
                        :style="column.width ? `width: ${column.width}` : undefined"
                    >
                        <div class="flex items-center space-x-1">
                            <span>{{ column.label }}</span>
                            <button
                                v-if="column.sortable"
                                :class="[
                                    'flex-shrink-0 h-4 w-4 text-gray-400 hover:text-gray-600',
                                    sortBy === column.key && sortDirection === 'asc' ? 'text-gray-600' : '',
                                    sortBy === column.key && sortDirection === 'desc' ? 'text-gray-600' : ''
                                ]"
                                @click="handleSort(column.key)"
                            >
                                <svg
                                    :class="[
                                        'h-4 w-4 transition-transform',
                                        sortBy === column.key && sortDirection === 'desc' ? 'rotate-180' : ''
                                    ]"
                                    fill="none"
                                    viewBox="0 0 24 24"
                                    stroke="currentColor"
                                >
                                    <path
                                        stroke-linecap="round"
                                        stroke-linejoin="round"
                                        stroke-width="2"
                                        d="M7 16V4m0 0L3 8m4-4l4 4m6 0v12m0 0l4-4m-4 4l-4-4"
                                    />
                                </svg>
                            </button>
                        </div>
                    </th>
                </tr>
            </thead>
            
            <tbody class="bg-white divide-y divide-gray-200">
                <tr
                    v-for="(row, index) in data"
                    :key="getRowKey(row, index)"
                    class="hover:bg-gray-50"
                >
                    <td
                        v-for="column in columns"
                        :key="column.key"
                        :class="[
                            'px-6 py-4 whitespace-nowrap text-sm text-gray-900',
                            column.class || ''
                        ]"
                    >
                        <slot
                            :name="`cell-${column.key}`"
                            :row="row"
                            :value="getColumnValue(row, column.key)"
                            :column="column"
                            :index="index"
                        >
                            {{ formatValue(getColumnValue(row, column.key), column) }}
                        </slot>
                    </td>
                </tr>
            </tbody>
        </table>
        
        <div v-if="loading" class="flex justify-center py-8">
            <LoadingSpinner size="lg" />
        </div>
        
        <div v-if="!loading && data.length === 0" class="text-center py-8">
            <p class="text-gray-500">No hay datos disponibles</p>
        </div>
    </div>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import LoadingSpinner from './LoadingSpinner.vue';

interface TableColumn {
    key: string;
    label: string;
    sortable?: boolean;
    width?: string;
    class?: string;
    formatter?: (value: any) => string;
}

interface Props {
    data: Record<string, any>[];
    columns: TableColumn[];
    loading?: boolean;
    sortBy?: string;
    sortDirection?: 'asc' | 'desc';
    rowKey?: string | ((row: Record<string, any>) => string | number);
}

const props = withDefaults(defineProps<Props>(), {
    loading: false,
    sortDirection: 'asc',
    rowKey: 'id',
});

const emit = defineEmits<{
    sort: [column: string];
}>();

const getRowKey = (row: Record<string, any>, index: number): string | number => {
    if (typeof props.rowKey === 'function') {
        return props.rowKey(row);
    }
    return row[props.rowKey] || index;
};

const getColumnValue = (row: Record<string, any>, key: string): any => {
    return key.split('.').reduce((obj, k) => obj?.[k], row);
};

const formatValue = (value: any, column: TableColumn): string => {
    if (column.formatter) {
        return column.formatter(value);
    }
    
    if (value === null || value === undefined) {
        return '';
    }
    
    if (typeof value === 'boolean') {
        return value ? 'Sí' : 'No';
    }
    
    return String(value);
};

const handleSort = (column: string) => {
    emit('sort', column);
};
</script>
